version: '2.0'

services:
  postgresqlserver:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: pgp4ssw0rd
    volumes:
    - pg-datavolume:/var/lib/postgresql

  booklist_razor_pages:
    image: booklist_razor_pages
    restart: always
    ports:
    - "8002:80"
    links:
    - postgresqlserver

volumes:
  pg-datavolume:

